import { useEffect, useState } from 'react'

export type Locale = 'zh-CN' | 'en-US'
type Values = Record<string, string | number>

const zh: Record<string, string> = {
  'app.tagline': '安全访问授权的 Web 资源', 'app.license': 'Tvpn 按 AGPL-3.0 提供且不附带担保。', 'app.source': '查看许可证与源代码',
  'nav.main': '主导航', 'nav.browser': '浏览', 'nav.users': '用户', 'nav.policies': '策略', 'nav.upstreams': '代理', 'nav.ldap': 'LDAP', 'nav.audit': '审计', 'nav.tokens': '程序令牌',
  'auth.username': '用户名', 'auth.password': '密码', 'auth.login': '登录', 'auth.logging_in': '正在登录', 'auth.logout': '退出登录',
  'browser.back': '后退', 'browser.forward': '前进', 'browser.reload': '刷新', 'browser.exit': '访问出口', 'browser.direct': '服务端直连', 'browser.no_exit': '无可用出口', 'browser.url': '网址', 'browser.url_placeholder': '输入网址或 IP 地址', 'browser.go': '访问', 'browser.compatibility': '兼容模式', 'browser.compatibility_help': '用于需要额外跨域兼容处理的网站', 'browser.frame_title': 'WebVPN 页面', 'browser.empty_title': '开始安全浏览', 'browser.empty_body': '在上方输入已获授权的网址',
  'common.create': '创建', 'common.save': '保存', 'common.cancel': '取消', 'common.edit': '编辑', 'common.delete': '删除', 'common.enable': '启用', 'common.disable': '禁用', 'common.enabled': '启用', 'common.disabled': '停用', 'common.status': '状态', 'common.actions': '操作', 'common.name': '名称', 'common.type': '类型', 'common.address': '地址', 'common.authentication': '认证', 'common.loading': '正在加载...', 'common.none': '无', 'common.not_applicable': '不适用', 'common.no_description': '无描述', 'common.system': '系统', 'common.operation_failed': '操作失败',
  'upstream.title': '访问出口', 'upstream.new': '新建代理', 'upstream.direct_body': '使用 Tvpn 服务器网络', 'upstream.local_network': '本机网络', 'upstream.acl_restricted': 'ACL 限制', 'upstream.all_users': '所有用户', 'upstream.authorized_users': '授权用户', 'upstream.authorized_groups': '授权 LDAP 组', 'upstream.users_updated': '直连用户授权已更新', 'upstream.groups_updated': '直连组授权已更新', 'upstream.direct_all': '直连已允许所有用户', 'upstream.acl_enabled': '直连 ACL 已启用', 'upstream.allow_all': '允许所有用户', 'upstream.enable_acl': '启用 ACL', 'upstream.password_configured': '密码已配置', 'upstream.no_auth': '无认证', 'upstream.user_grants_updated': '用户授权已更新', 'upstream.group_grants_updated': '组授权已更新', 'upstream.confirm_delete': '删除代理“{name}”？活动中的相关浏览上下文也会关闭。', 'upstream.deleted': '代理已删除', 'upstream.saved': '代理已保存', 'upstream.edit_title': '编辑上游代理', 'upstream.new_title': '新建上游代理', 'upstream.host': '主机或 IP', 'upstream.port': '端口', 'upstream.password_keep': '留空则保留现有密码', 'upstream.optional': '可选', 'upstream.enable': '启用代理', 'upstream.clear_password': '清除已保存的密码',
  'users.title': '用户', 'users.new': '新建用户', 'users.source': '来源', 'users.role': '角色', 'users.policy': '策略', 'users.admin': '管理员', 'users.user': '用户', 'users.normal': '正常', 'users.policy_updated': '用户策略已更新', 'users.created': '用户已创建', 'users.new_local': '新建本地用户', 'users.display_name': '显示名称', 'users.email': '邮箱', 'users.initial_password': '初始密码',
  'policy.title': '访问策略', 'policy.new': '新建策略', 'policy.mode': '模式', 'policy.rules': '规则', 'policy.deleted': '策略已删除', 'policy.saved': '策略已保存', 'policy.confirm_delete': '删除策略“{name}”？', 'policy.edit': '编辑策略', 'policy.description': '描述', 'policy.rule_input': '域名、URL 前缀或 CIDR 规则', 'policy.enable': '启用策略', 'policy.deny_all': '禁止访问', 'policy.deny_intranet': '禁止内网', 'policy.whitelist': '白名单', 'policy.blacklist': '黑名单', 'policy.assigned_count': '{count} 项策略', 'policy.unassigned': '未分配',
  'ldap.connection': '目录连接', 'ldap.secret_note': '密码和 CA 证书仅从容器 Secret 文件读取', 'ldap.auth_mode': '认证模式', 'ldap.search_bind': '搜索绑定', 'ldap.dn_template': 'DN 模板', 'ldap.start_tls': '使用 StartTLS', 'ldap.url': 'LDAP URL', 'ldap.user_base_dn': '用户 Base DN', 'ldap.bind_dn': '服务绑定 DN', 'ldap.user_filter': '用户过滤器', 'ldap.user_dn_template': '用户 DN 模板', 'ldap.username_attribute': '用户名属性', 'ldap.display_name_attribute': '显示名称属性', 'ldap.email_attribute': '邮箱属性', 'ldap.group_base_dn': '组 Base DN', 'ldap.group_filter': '组过滤器', 'ldap.group_name_attribute': '组名称属性', 'ldap.saved': 'LDAP 配置已保存', 'ldap.test': '测试连接', 'ldap.success': 'LDAP 连接成功', 'ldap.save': '保存配置', 'ldap.synced_groups': '已同步组', 'ldap.group': '组', 'ldap.last_sync': '最后同步', 'ldap.group_policy_updated': '组策略已更新',
  'audit.title': '审计日志', 'audit.time': '时间', 'audit.event': '事件', 'audit.result': '结果', 'audit.target': '目标', 'audit.actor': '操作者',
  'picker.count': '{count} 项', 'picker.empty': '无{label}', 'picker.no_options': '暂无可选项',
  'tokens.title': '程序令牌', 'tokens.new': '新建令牌', 'tokens.name': '用途名称', 'tokens.prefix': '前缀', 'tokens.scopes': '权限', 'tokens.expires': '过期时间', 'tokens.last_used': '最后使用', 'tokens.never': '从未使用', 'tokens.proxy_scope': '代理访问', 'tokens.admin_scope': '管理接口', 'tokens.created': '令牌已创建', 'tokens.revoked': '令牌已撤销', 'tokens.secret_title': '立即保存令牌', 'tokens.secret_once': '该令牌只显示一次，关闭后无法再次查看。', 'tokens.copy': '复制令牌', 'tokens.copied': '已复制', 'tokens.confirm_revoke': '撤销令牌“{name}”？使用它的程序将立即失去访问权限。',
	'locale.switch': 'Switch to English', 'error.common.request_failed': '请求失败',
	'error.auth.admin_required': '需要管理员权限', 'error.auth.csrf_failed': 'CSRF 校验失败', 'error.auth.invalid_credentials': '用户名或密码错误', 'error.auth.invalid_scope': '令牌权限范围无效', 'error.auth.invalid_token': '程序令牌无效或已过期', 'error.auth.scope_required': '程序令牌缺少所需权限', 'error.auth.token_not_found': '程序令牌不存在', 'error.auth.unauthorized': '需要登录或程序令牌',
	'error.common.internal': '服务器内部错误', 'error.common.invalid_id': 'ID 格式无效', 'error.common.invalid_request': '请求格式无效', 'error.common.method_not_allowed': '请求方法不受支持', 'error.common.misdirected_request': '请求 Host 不属于此服务', 'error.common.not_found': '资源不存在', 'error.common.web_unavailable': 'Web 界面不可用',
	'error.admin.invalid_assignment': '资源授权无效', 'error.admin.invalid_ldap': 'LDAP 配置无效', 'error.admin.invalid_password': '密码不符合要求', 'error.admin.invalid_policy': '访问策略无效', 'error.admin.invalid_upstream_proxy': '上游代理配置无效', 'error.admin.invalid_user': '用户配置无效', 'error.admin.last_admin': '不能禁用或降级最后一个管理员', 'error.admin.ldap_unavailable': 'LDAP 连接或服务绑定失败', 'error.admin.upstream_proxy_not_found': '上游代理不存在',
	'error.proxy.authentication_required': '需要有效的程序令牌或代理会话', 'error.proxy.context_not_found': '代理上下文不存在', 'error.proxy.direct_access_denied': '未获授权使用服务端直连', 'error.proxy.invalid_cookie': 'Cookie 格式无效', 'error.proxy.invalid_target': '目标 URL 无效', 'error.proxy.invalid_ticket': '代理票据无效或已使用', 'error.proxy.redirect_denied': '访问策略拒绝重定向目标', 'error.proxy.rewrite_failed': '目标页面无法安全改写', 'error.proxy.route_not_found': '代理路由不存在', 'error.proxy.session_invalid': '代理会话已失效', 'error.proxy.target_denied': '访问策略拒绝该目标', 'error.proxy.target_unavailable': '目标地址不可用', 'error.proxy.upstream_error': '连接目标站点失败', 'error.proxy.upstream_proxy_denied': '未获授权或代理已停用', 'error.proxy.upstream_proxy_unavailable': '上游代理不可用或授权已撤销', 'error.proxy.websocket_upstream_failed': '无法连接上游 WebSocket',
	'error.proxy.mux.invalid_frame': '代理通道帧无效', 'error.proxy.mux.duplicate_stream': '代理通道流已存在', 'error.proxy.mux.invalid_metadata': '代理请求元数据无效', 'error.proxy.mux.body_too_large': '代理请求正文超过限制', 'error.proxy.mux.unsupported_method': '代理请求方法不受支持', 'error.proxy.mux.response_interrupted': '上游响应意外中断',
}

const en: Record<string, string> = {
  'app.tagline': 'Secure access to authorized web resources', 'app.license': 'Tvpn is provided under AGPL-3.0 without warranty.', 'app.source': 'View license and source code',
  'nav.main': 'Main navigation', 'nav.browser': 'Browse', 'nav.users': 'Users', 'nav.policies': 'Policies', 'nav.upstreams': 'Egress', 'nav.ldap': 'LDAP', 'nav.audit': 'Audit', 'nav.tokens': 'API tokens',
  'auth.username': 'Username', 'auth.password': 'Password', 'auth.login': 'Sign in', 'auth.logging_in': 'Signing in', 'auth.logout': 'Sign out',
  'browser.back': 'Back', 'browser.forward': 'Forward', 'browser.reload': 'Reload', 'browser.exit': 'Egress', 'browser.direct': 'Direct server access', 'browser.no_exit': 'No available egress', 'browser.url': 'URL', 'browser.url_placeholder': 'Enter a URL or IP address', 'browser.go': 'Open', 'browser.compatibility': 'Compatibility mode', 'browser.compatibility_help': 'Use for sites that need additional cross-origin compatibility', 'browser.frame_title': 'WebVPN page', 'browser.empty_title': 'Start secure browsing', 'browser.empty_body': 'Enter an authorized URL above',
  'common.create': 'Create', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.edit': 'Edit', 'common.delete': 'Delete', 'common.enable': 'Enable', 'common.disable': 'Disable', 'common.enabled': 'Enabled', 'common.disabled': 'Disabled', 'common.status': 'Status', 'common.actions': 'Actions', 'common.name': 'Name', 'common.type': 'Type', 'common.address': 'Address', 'common.authentication': 'Authentication', 'common.loading': 'Loading...', 'common.none': 'None', 'common.not_applicable': 'N/A', 'common.no_description': 'No description', 'common.system': 'System', 'common.operation_failed': 'Operation failed',
  'upstream.title': 'Egress', 'upstream.new': 'New proxy', 'upstream.direct_body': 'Use the Tvpn server network', 'upstream.local_network': 'Local network', 'upstream.acl_restricted': 'ACL restricted', 'upstream.all_users': 'All users', 'upstream.authorized_users': 'Authorized users', 'upstream.authorized_groups': 'Authorized LDAP groups', 'upstream.users_updated': 'Direct user grants updated', 'upstream.groups_updated': 'Direct group grants updated', 'upstream.direct_all': 'Direct access is open to all users', 'upstream.acl_enabled': 'Direct access ACL enabled', 'upstream.allow_all': 'Allow all users', 'upstream.enable_acl': 'Enable ACL', 'upstream.password_configured': 'Password configured', 'upstream.no_auth': 'No authentication', 'upstream.user_grants_updated': 'User grants updated', 'upstream.group_grants_updated': 'Group grants updated', 'upstream.confirm_delete': 'Delete proxy “{name}”? Related active browsing contexts will also close.', 'upstream.deleted': 'Proxy deleted', 'upstream.saved': 'Proxy saved', 'upstream.edit_title': 'Edit upstream proxy', 'upstream.new_title': 'New upstream proxy', 'upstream.host': 'Host or IP', 'upstream.port': 'Port', 'upstream.password_keep': 'Leave blank to keep the existing password', 'upstream.optional': 'Optional', 'upstream.enable': 'Enable proxy', 'upstream.clear_password': 'Clear saved password',
  'users.title': 'Users', 'users.new': 'New user', 'users.source': 'Source', 'users.role': 'Role', 'users.policy': 'Policy', 'users.admin': 'Administrator', 'users.user': 'User', 'users.normal': 'Active', 'users.policy_updated': 'User policies updated', 'users.created': 'User created', 'users.new_local': 'New local user', 'users.display_name': 'Display name', 'users.email': 'Email', 'users.initial_password': 'Initial password',
  'policy.title': 'Access policies', 'policy.new': 'New policy', 'policy.mode': 'Mode', 'policy.rules': 'Rules', 'policy.deleted': 'Policy deleted', 'policy.saved': 'Policy saved', 'policy.confirm_delete': 'Delete policy “{name}”?', 'policy.edit': 'Edit policy', 'policy.description': 'Description', 'policy.rule_input': 'Domain, URL prefix, or CIDR rules', 'policy.enable': 'Enable policy', 'policy.deny_all': 'Deny all', 'policy.deny_intranet': 'Deny private networks', 'policy.whitelist': 'Allowlist', 'policy.blacklist': 'Blocklist', 'policy.assigned_count': '{count} policies', 'policy.unassigned': 'Unassigned',
  'ldap.connection': 'Directory connection', 'ldap.secret_note': 'Passwords and CA certificates are read only from container secrets', 'ldap.auth_mode': 'Authentication mode', 'ldap.search_bind': 'Search bind', 'ldap.dn_template': 'DN template', 'ldap.start_tls': 'Use StartTLS', 'ldap.url': 'LDAP URL', 'ldap.user_base_dn': 'User Base DN', 'ldap.bind_dn': 'Service bind DN', 'ldap.user_filter': 'User filter', 'ldap.user_dn_template': 'User DN template', 'ldap.username_attribute': 'Username attribute', 'ldap.display_name_attribute': 'Display name attribute', 'ldap.email_attribute': 'Email attribute', 'ldap.group_base_dn': 'Group Base DN', 'ldap.group_filter': 'Group filter', 'ldap.group_name_attribute': 'Group name attribute', 'ldap.saved': 'LDAP settings saved', 'ldap.test': 'Test connection', 'ldap.success': 'LDAP connection succeeded', 'ldap.save': 'Save settings', 'ldap.synced_groups': 'Synchronized groups', 'ldap.group': 'Group', 'ldap.last_sync': 'Last synchronized', 'ldap.group_policy_updated': 'Group policies updated',
  'audit.title': 'Audit log', 'audit.time': 'Time', 'audit.event': 'Event', 'audit.result': 'Result', 'audit.target': 'Target', 'audit.actor': 'Actor',
  'picker.count': '{count} items', 'picker.empty': 'No {label}', 'picker.no_options': 'No options available',
  'tokens.title': 'API tokens', 'tokens.new': 'New token', 'tokens.name': 'Purpose', 'tokens.prefix': 'Prefix', 'tokens.scopes': 'Scopes', 'tokens.expires': 'Expires', 'tokens.last_used': 'Last used', 'tokens.never': 'Never', 'tokens.proxy_scope': 'Proxy access', 'tokens.admin_scope': 'Administration API', 'tokens.created': 'Token created', 'tokens.revoked': 'Token revoked', 'tokens.secret_title': 'Save this token now', 'tokens.secret_once': 'This token is shown only once and cannot be retrieved after closing.', 'tokens.copy': 'Copy token', 'tokens.copied': 'Copied', 'tokens.confirm_revoke': 'Revoke token “{name}”? Programs using it will immediately lose access.',
	'locale.switch': '切换到中文', 'error.common.request_failed': 'Request failed',
	'error.auth.admin_required': 'Administrator access is required', 'error.auth.csrf_failed': 'CSRF validation failed', 'error.auth.invalid_credentials': 'Invalid username or password', 'error.auth.invalid_scope': 'Token scope is invalid', 'error.auth.invalid_token': 'Program token is invalid or expired', 'error.auth.scope_required': 'Program token lacks the required scope', 'error.auth.token_not_found': 'Program token was not found', 'error.auth.unauthorized': 'Authentication is required',
	'error.common.internal': 'Internal server error', 'error.common.invalid_id': 'ID is invalid', 'error.common.invalid_request': 'Request is invalid', 'error.common.method_not_allowed': 'Method is not allowed', 'error.common.misdirected_request': 'Request host does not belong to this service', 'error.common.not_found': 'Resource was not found', 'error.common.web_unavailable': 'Web interface is unavailable',
	'error.admin.invalid_assignment': 'Resource assignment is invalid', 'error.admin.invalid_ldap': 'LDAP configuration is invalid', 'error.admin.invalid_password': 'Password does not meet requirements', 'error.admin.invalid_policy': 'Access policy is invalid', 'error.admin.invalid_upstream_proxy': 'Upstream proxy configuration is invalid', 'error.admin.invalid_user': 'User configuration is invalid', 'error.admin.last_admin': 'The last administrator cannot be disabled or demoted', 'error.admin.ldap_unavailable': 'LDAP connection or service bind failed', 'error.admin.upstream_proxy_not_found': 'Upstream proxy was not found',
	'error.proxy.authentication_required': 'A valid program token or proxy session is required', 'error.proxy.context_not_found': 'Proxy context was not found', 'error.proxy.direct_access_denied': 'Direct server access is not authorized', 'error.proxy.invalid_cookie': 'Cookie is invalid', 'error.proxy.invalid_target': 'Target URL is invalid', 'error.proxy.invalid_ticket': 'Proxy ticket is invalid or already used', 'error.proxy.redirect_denied': 'Redirect target was denied by policy', 'error.proxy.rewrite_failed': 'Target page could not be rewritten safely', 'error.proxy.route_not_found': 'Proxy route was not found', 'error.proxy.session_invalid': 'Proxy session has expired', 'error.proxy.target_denied': 'Target was denied by policy', 'error.proxy.target_unavailable': 'Target is unavailable', 'error.proxy.upstream_error': 'Failed to connect to target', 'error.proxy.upstream_proxy_denied': 'Upstream proxy is disabled or not authorized', 'error.proxy.upstream_proxy_unavailable': 'Upstream proxy is unavailable or authorization was revoked', 'error.proxy.websocket_upstream_failed': 'Failed to connect to upstream WebSocket',
	'error.proxy.mux.invalid_frame': 'Invalid proxy channel frame', 'error.proxy.mux.duplicate_stream': 'Proxy channel stream already exists', 'error.proxy.mux.invalid_metadata': 'Invalid proxy request metadata', 'error.proxy.mux.body_too_large': 'Proxy request body exceeds the limit', 'error.proxy.mux.unsupported_method': 'Proxy request method is not supported', 'error.proxy.mux.response_interrupted': 'Upstream response was interrupted',
}

const dictionaries = { 'zh-CN': zh, 'en-US': en }
const storedLocale = typeof localStorage === 'undefined' ? null : localStorage.getItem('tvpn.locale') as Locale | null
const browserLanguage = typeof navigator === 'undefined' ? 'zh-CN' : navigator.language
let locale: Locale = storedLocale || (browserLanguage.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en-US')

export function t(id: string, values: Values = {}): string {
  const template = dictionaries[locale][id] || dictionaries['zh-CN'][id] || id
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`))
}
export function hasTranslation(id: string) { return Boolean(dictionaries[locale][id] || dictionaries['zh-CN'][id]) }
export function currentLocale() { return locale }
export function setLocale(value: Locale) { locale = value; if (typeof localStorage !== 'undefined') localStorage.setItem('tvpn.locale', value); if (typeof window !== 'undefined') window.dispatchEvent(new Event('tvpn:locale')) }
export function missingTranslations() { const ids = new Set([...Object.keys(zh), ...Object.keys(en)]); return [...ids].filter(id => !zh[id] || !en[id]) }
export function useLocale() { const [, update] = useState(locale); useEffect(() => { const listener = () => update(locale); addEventListener('tvpn:locale', listener); return () => removeEventListener('tvpn:locale', listener) }, []); return locale }
